import { Activity, BarChart3, Binary, Gauge } from "lucide-react";
import { NavLink } from "react-router-dom";

const navigation = [
  { to: "/dashboard", label: "Dashboard", icon: Gauge },
  { to: "/predict", label: "Prediction", icon: Binary },
  { to: "/visualizations", label: "Visualizations", icon: BarChart3 },
];

export default function Layout({ children }) {
  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-mark">
            <Activity size={20} />
          </div>
          <div>
            <p className="brand-eyebrow">Multi-Sensor QA</p>
            <h1>Defect Intelligence</h1>
          </div>
        </div>

        <nav className="nav-links">
          {navigation.map(({ to, label, icon: Icon }) => (
            <NavLink
              key={to}
              to={to}
              className={({ isActive }) => `nav-link ${isActive ? "active" : ""}`}
            >
              <Icon size={18} />
              <span>{label}</span>
            </NavLink>
          ))}
        </nav>

        <div className="sidebar-panel">
          <p className="sidebar-title">Purpose</p>
          <p>
            Inspect live predictions, compare models, and review training artifacts generated by
            the FastAPI-backed defect detection pipeline.
          </p>
        </div>
      </aside>

      <main className="page-shell">
        <div className="page-background" />
        {children}
      </main>
    </div>
  );
}
