import { useEffect, useMemo, useState } from "react";
import MetricsBarChart from "../components/MetricsBarChart";
import ModelComparisonChart from "../components/ModelComparisonChart";
import StatCard from "../components/StatCard";
import StatusPill from "../components/StatusPill";
import { getSummary } from "../services/api";
import { formatCount, formatPercent } from "../utils/formatters";

export default function DashboardPage() {
  const [summary, setSummary] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    getSummary()
      .then(setSummary)
      .catch(() => setError("Unable to load artifact summary from the FastAPI backend."));
  }, []);

  const comparisonRows = useMemo(() => {
    if (!summary?.comparison) {
      return [];
    }
    return [
      {
        model: "XGBoost",
        accuracy: summary.comparison.xgboost?.accuracy ?? 0,
      },
      {
        model: "LSTM Fusion",
        accuracy: summary.comparison.fusion?.accuracy ?? 0,
      },
    ];
  }, [summary]);

  const metricRows = useMemo(() => {
    if (!summary?.comparison) {
      return [];
    }
    return [
      {
        metric: "Precision",
        XGBoost: summary.comparison.xgboost?.precision ?? 0,
        "LSTM Fusion": summary.comparison.fusion?.precision ?? 0,
      },
      {
        metric: "Recall",
        XGBoost: summary.comparison.xgboost?.recall ?? 0,
        "LSTM Fusion": summary.comparison.fusion?.recall ?? 0,
      },
      {
        metric: "F1",
        XGBoost: summary.comparison.xgboost?.f1_score ?? 0,
        "LSTM Fusion": summary.comparison.fusion?.f1_score ?? 0,
      },
      {
        metric: "ROC-AUC",
        XGBoost: summary.comparison.xgboost?.roc_auc ?? 0,
        "LSTM Fusion": summary.comparison.fusion?.roc_auc ?? 0,
      },
    ];
  }, [summary]);

  const totalSamples = summary?.metadata?.dataset_summary?.rows ?? 0;
  const apiHealthy = summary?.health?.status === "ok";

  return (
    <section className="page">
      <header className="hero-card">
        <div>
          <p className="hero-kicker">Production Monitoring</p>
          <h2>Defect Detection Control Center</h2>
          <p className="hero-copy">
            Track model quality, monitor backend readiness, and compare the classical baseline
            against the LSTM fusion model using artifacts generated by the FastAPI pipeline.
          </p>
        </div>
        <StatusPill healthy={apiHealthy} />
      </header>

      {error ? <div className="form-error">{error}</div> : null}

      <section className="stats-grid">
        <StatCard
          title="Dataset Rows"
          value={formatCount(totalSamples)}
          subtitle="Cycles available in the Parquet dataset"
          accent="orange"
        />
        <StatCard
          title="Baseline Accuracy"
          value={formatPercent(summary?.comparison?.xgboost?.accuracy)}
          subtitle="XGBoost performance on the held-out test split"
          accent="blue"
        />
        <StatCard
          title="Fusion F1 Score"
          value={formatPercent(summary?.comparison?.fusion?.f1_score)}
          subtitle="LSTM fusion quality on the held-out test split"
          accent="green"
        />
        <StatCard
          title="Best Fusion Epoch"
          value={summary?.comparison?.fusion?.best_epoch ?? "--"}
          subtitle="Early stopping checkpoint selected for deployment"
          accent="rose"
        />
      </section>

      <section className="content-grid two-up">
        <ModelComparisonChart data={comparisonRows} />
        <div className="insight-card">
          <p className="section-kicker">Current Run</p>
          <h3>Model outcome summary</h3>
          <ul className="insight-list">
            <li>
              XGBoost currently achieves {formatPercent(summary?.comparison?.xgboost?.accuracy)} accuracy and{" "}
              {formatPercent(summary?.comparison?.xgboost?.f1_score)} F1.
            </li>
            <li>
              The LSTM fusion model reaches {formatPercent(summary?.comparison?.fusion?.accuracy)} accuracy and{" "}
              {formatPercent(summary?.comparison?.fusion?.f1_score)} F1.
            </li>
            <li>
              Fusion beats baseline: {summary?.comparison?.fusion_beats_xgboost ? "Yes" : "No"} on the latest split.
            </li>
            <li>
              API artifacts ready: {summary?.health?.artifacts_ready === "true" ? "Yes" : "No"}.
            </li>
          </ul>
        </div>
      </section>

      <MetricsBarChart data={metricRows} />
    </section>
  );
}
